# Generated by Django 3.1.4 on 2020-12-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
