# Generated by Django 3.1.4 on 2020-12-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_subcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
    ]
