# Generated by Django 3.1.4 on 2021-01-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_pictureproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(default=None, upload_to='', verbose_name='Изображение'),
        ),
    ]
