# Generated by Django 3.1.4 on 2021-01-08 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0005_auto_20201210_0149'),
        ('product', '0010_pictureproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeatureitem',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.productcolor', verbose_name='Цвет'),
        ),
    ]
