# Generated by Django 3.1.4 on 2021-01-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20210110_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfeature',
            options={'verbose_name': 'Характеристика к товару', 'verbose_name_plural': 'Характеристики к товарам'},
        ),
        migrations.AlterModelOptions(
            name='productfeatureitem',
            options={'verbose_name': 'Особенность характеристики к товару', 'verbose_name_plural': 'Особенности характеристики к товарам'},
        ),
        migrations.AlterField(
            model_name='pictureproduct',
            name='image',
            field=models.FileField(default=None, upload_to='', verbose_name='Изображение'),
        ),
    ]
