# Generated by Django 3.1.4 on 2021-01-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20210112_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cloth',
            field=models.CharField(max_length=64, null=True, verbose_name='Полотно'),
        ),
        migrations.AddField(
            model_name='product',
            name='structure',
            field=models.CharField(max_length=64, null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_of_finishing',
            field=models.CharField(max_length=64, null=True, verbose_name='Вид отделки'),
        ),
    ]
