# Generated by Django 3.0.6 on 2020-12-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCollection',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='color_hex',
        ),
        migrations.AddField(
            model_name='productcolor',
            name='value',
            field=models.CharField(default='000000', max_length=6, verbose_name='Цвет в формате HEX (#000fff)'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Название цвета'),
        ),
        migrations.AlterField(
            model_name='productheight',
            name='value',
            field=models.IntegerField(unique=True, verbose_name='Значение высоты'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='value',
            field=models.IntegerField(unique=True, verbose_name='Значение размера'),
        ),
    ]
