# Generated by Django 3.1.4 on 2020-12-09 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_auto_20201210_0132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolor',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AlterModelOptions(
            name='productheight',
            options={'verbose_name': 'Высота', 'verbose_name_plural': 'Высота'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
    ]
