# Generated by Django 3.1.4 on 2021-01-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0005_auto_20201210_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='value',
            field=models.CharField(default=None, max_length=6, null=True, verbose_name='Цвет в формате HEX (000fff)'),
        ),
    ]
