# Generated by Django 3.1.4 on 2021-01-12 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20210112_2110'),
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='products',
        ),
        migrations.CreateModel(
            name='FeatureCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.card')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('product_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productfeature')),
                ('product_feature_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productfeatureitem')),
            ],
        ),
    ]
