# Generated by Django 3.1.4 on 2021-01-14 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_auto_20210112_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurecard',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='card.order'),
        ),
    ]
