# Generated by Django 3.1.4 on 2021-01-14 20:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_auto_20210114_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
