# Generated by Django 3.1.4 on 2021-01-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_order_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(null=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, null=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='initials',
            field=models.CharField(max_length=128, null=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=24, null=None),
        ),
    ]
